
backend:
  name: github
  repo: magik03/abouseradjVip # تأكد أن هذا اسم حسابك ومستودعك
  branch: main

media_folder: "images" # مجلد الصور

collections:
  - name: "blog"
    label: "المقالات"
    folder: "_posts"
    create: true
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
