
backend:
  name: github
  repo: magik03/abouseradjVip
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "links"
    label: "الروابط والتطبيقات"
    folder: "content/links"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "اسم التطبيق", name: "title", widget: "string"}
      - {label: "التصنيف", name: "category", widget: "select", options: ["أندرويد", "موقع ويب", "آيفون"]}
      - {label: "الرابط المباشر", name: "url", widget: "string"}
      - {label: "الوصف", name: "body", widget: "text"}
